---
- hosts: web
  become: yes
  become_user: root

  tasks:
  - name: Install remi repo.
    yum:
      name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
      state: present

  - name: Import remi GPG key.
    rpm_key:
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      state: present

  - name: Install httpd and php 7.3 and module  
    yum:
      name:
        - httpd
        - php
        - php-cli
        - php-fpm 
        - php-mysqlnd
        - php-zip
        - php-devel
        - php-gd
        - php-mcrypt
        - php-mbstring
        - php-curl
        - php-xml
        - php-pear
        - php-bcmath
        - php-json
      state: latest
      enablerepo: remi-php73  

  - name: Edit file Timezone
    lineinfile:
     path: /etc/php.ini
     regexp: ';date.timezone'
     line: 'date.timezone = Asia/Bangkok'
     backup: yes

  - name: Enable service httpd
    service:
        name: httpd
        enabled: yes

  - name: Start service httpd
    service:
        name: httpd
        state: started

  - name: Enable firewalld
    service:
        name: firewalld
        enabled: yes
    
  - name: Start firewall
    service:
        name: firewalld
        state: started
    
  - name: Open firewall service http and https
    firewalld:
        service: '{{ item }}'
        permanent: yes
        state: enabled
    loop:
        - "http"
        - "https"

  - name: Restart firewalld
    service:
        name:  firewalld
        state:  restarted

  - name: Copy index.php to web.server
    template:
     src: template/index.php.j2
     dest: /var/www/html/index.php
     owner: root
     group: root
     mode: 0755

- hosts: db
  become: yes
  become_user: root
  tasks:

  - name: Install maria-db
    yum:
      name: mariadb-server
      state: latest

  - name: Enable service httpd
    service:
      name: mariadb
      enabled: yes
    
  - name: Start service httpd
    service:
      name: mariadb
      state: started

  - name: Enable firewall
    service:
      name: firewalld
      enabled: yes

  - name: Start firewall
    service:
      name: firewalld
      state: started

  - name: Open firewall
    firewalld:
      port: '{{ item }}'
      permanent: yes
      state: enabled
    loop:
      - "3306/tcp"

  - name: Restart firewall
    service:
      name: firewalld
      state: restarted
    
    
  - name: Copy resolv file nameserver
    template:
     src: template/resolv-mgn.conf.j2
     dest: /etc/resolv.conf
     owner: root
     group: root
     mode: "0644"
    when: ansible_connection == 'local'